# Generated by Django 4.2.2 on 2023-07-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='field1',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='contact',
            name='field2',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='contact',
            name='field3',
            field=models.IntegerField(default=None),
        ),
    ]
