# Generated by Django 4.2.2 on 2023-07-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_field3_contact_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='field1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='field2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='result',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
